version: '3.8'

services:
  backend:
    image: docker.io/naglissul/bankas-skafis-api:latest
    ports:
      - "9000:9000"
    environment:
      - FIREBASE_SERVICE_ACCOUNT_PATH=/etc/secrets/firebase-admin.json
      - ENVIRONMENT=dev
      - PORT=9000
    volumes:
      - /local/path/to/firebase-admin.json:/etc/secrets/firebase-admin.json
