version: '3.8'

services:
  backend:
    image: docker.io/naglissul/bankas-skafis-api:latest
    ports:
      - "8080:8080"
    environment:
      - FIREBASE_SERVICE_ACCOUNT_PATH=/etc/secrets/firebase-admin.json
    volumes:
      - path/on/your/device/firebase-admin.json:/etc/secrets/firebase-admin.json
