name: Trigger every 10 minutes (15 minutes till shuts down)

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  send_requests:
    runs-on: ubuntu-latest

    steps:
      - name: Send HTTP GET request
        run: |
          curl -X GET "https://api.bankas.skafis.lt/misc/triggerService"
